/* ============================================================================
 * MODEL CONFIGURATION
 * Case: 3D droplet on flat surface (wetting verification)
 * ========================================================================== */

/* --------------------- VELOCITY SET --------------------- */
#define D3Q19

/* --------------------- COLLISION METHOD --------------------- */
#define COLLISION_TYPE MR_LBM_2ND_ORDER

/* --------------------- OTHER DEFINITIONS --------------------- */
#define RANDOM_NUMBERS false
#define TREAT_DATA_INCLUDE
